<?php

function slider_block_block_info() {
  // This example comes from node.module.

  $blocks['slider_block'] = array(
      'info' => t('[Tabvn] Slider block'),
          // DRUPAL_CACHE_PER_ROLE will be assumed.
  );

  return $blocks;
}

function slider_block_block_view($delta = '') {

  $block = array();

  switch ($delta) {


    case 'slider_block':
      $block['subject'] = '';
      $nids = db_query("SELECT n.nid FROM {node} n WHERE n.type = :type AND n.status = 1 ORDER BY n.created DESC", array(":type" => 'slider'))->fetchCol();
      if (!empty($nids)) {
        $nodes = node_load_multiple($nids);
        $block['content'] = array(
            '#theme' => 'slider_block',
            '#nodes' => $nodes,
        );
      }
      break;
  }
  return $block;
}

function slider_block_theme($existing, $type, $theme, $path) {
  return array(
      'slider_block' => array(
          'variables' => array('nodes' => NULL),
          'template' => 'slider_block',
      ),
  );
}
